// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: marketplace/product/v1/product.proto

package productv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetProductsRequest identifies the products to retrieve.
type GetProductsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// product_ids contains the stable product identifiers requested by the caller.
	ProductIds    []string `protobuf:"bytes,1,rep,name=product_ids,json=productIds,proto3" json:"product_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsRequest) Reset() {
	*x = GetProductsRequest{}
	mi := &file_marketplace_product_v1_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsRequest) ProtoMessage() {}

func (x *GetProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_product_v1_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsRequest.ProtoReflect.Descriptor instead.
func (*GetProductsRequest) Descriptor() ([]byte, []int) {
	return file_marketplace_product_v1_product_proto_rawDescGZIP(), []int{0}
}

func (x *GetProductsRequest) GetProductIds() []string {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

// GetProductsResponse contains the product snapshots that were found.
type GetProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsResponse) Reset() {
	*x = GetProductsResponse{}
	mi := &file_marketplace_product_v1_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsResponse) ProtoMessage() {}

func (x *GetProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_product_v1_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsResponse.ProtoReflect.Descriptor instead.
func (*GetProductsResponse) Descriptor() ([]byte, []int) {
	return file_marketplace_product_v1_product_proto_rawDescGZIP(), []int{1}
}

func (x *GetProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

// Product is an immutable product snapshot suitable for order pricing.
type Product struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ProductId string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	SellerId  string                 `protobuf:"bytes,2,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	Name      string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// unit_price_minor stores money in the currency's minor unit, never as floating point.
	UnitPriceMinor int64  `protobuf:"varint,4,opt,name=unit_price_minor,json=unitPriceMinor,proto3" json:"unit_price_minor,omitempty"`
	Currency       string `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Active         bool   `protobuf:"varint,6,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_marketplace_product_v1_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_product_v1_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_marketplace_product_v1_product_proto_rawDescGZIP(), []int{2}
}

func (x *Product) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *Product) GetSellerId() string {
	if x != nil {
		return x.SellerId
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetUnitPriceMinor() int64 {
	if x != nil {
		return x.UnitPriceMinor
	}
	return 0
}

func (x *Product) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Product) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

var File_marketplace_product_v1_product_proto protoreflect.FileDescriptor

const file_marketplace_product_v1_product_proto_rawDesc = "" +
	"\n" +
	"$marketplace/product/v1/product.proto\x12\x16marketplace.product.v1\"5\n" +
	"\x12GetProductsRequest\x12\x1f\n" +
	"\vproduct_ids\x18\x01 \x03(\tR\n" +
	"productIds\"R\n" +
	"\x13GetProductsResponse\x12;\n" +
	"\bproducts\x18\x01 \x03(\v2\x1f.marketplace.product.v1.ProductR\bproducts\"\xb7\x01\n" +
	"\aProduct\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1b\n" +
	"\tseller_id\x18\x02 \x01(\tR\bsellerId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12(\n" +
	"\x10unit_price_minor\x18\x04 \x01(\x03R\x0eunitPriceMinor\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06active\x18\x06 \x01(\bR\x06active2x\n" +
	"\x0eProductService\x12f\n" +
	"\vGetProducts\x12*.marketplace.product.v1.GetProductsRequest\x1a+.marketplace.product.v1.GetProductsResponseBLZJgithub.com/kitphon/marketplace-order-system/contracts/product/v1;productv1b\x06proto3"

var (
	file_marketplace_product_v1_product_proto_rawDescOnce sync.Once
	file_marketplace_product_v1_product_proto_rawDescData []byte
)

func file_marketplace_product_v1_product_proto_rawDescGZIP() []byte {
	file_marketplace_product_v1_product_proto_rawDescOnce.Do(func() {
		file_marketplace_product_v1_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_marketplace_product_v1_product_proto_rawDesc), len(file_marketplace_product_v1_product_proto_rawDesc)))
	})
	return file_marketplace_product_v1_product_proto_rawDescData
}

var file_marketplace_product_v1_product_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_marketplace_product_v1_product_proto_goTypes = []any{
	(*GetProductsRequest)(nil),  // 0: marketplace.product.v1.GetProductsRequest
	(*GetProductsResponse)(nil), // 1: marketplace.product.v1.GetProductsResponse
	(*Product)(nil),             // 2: marketplace.product.v1.Product
}
var file_marketplace_product_v1_product_proto_depIdxs = []int32{
	2, // 0: marketplace.product.v1.GetProductsResponse.products:type_name -> marketplace.product.v1.Product
	0, // 1: marketplace.product.v1.ProductService.GetProducts:input_type -> marketplace.product.v1.GetProductsRequest
	1, // 2: marketplace.product.v1.ProductService.GetProducts:output_type -> marketplace.product.v1.GetProductsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_marketplace_product_v1_product_proto_init() }
func file_marketplace_product_v1_product_proto_init() {
	if File_marketplace_product_v1_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_marketplace_product_v1_product_proto_rawDesc), len(file_marketplace_product_v1_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_marketplace_product_v1_product_proto_goTypes,
		DependencyIndexes: file_marketplace_product_v1_product_proto_depIdxs,
		MessageInfos:      file_marketplace_product_v1_product_proto_msgTypes,
	}.Build()
	File_marketplace_product_v1_product_proto = out.File
	file_marketplace_product_v1_product_proto_goTypes = nil
	file_marketplace_product_v1_product_proto_depIdxs = nil
}
