BUF_VERSION := v1.72.0
BUF := env GOWORK=off go run github.com/bufbuild/buf/cmd/buf@$(BUF_VERSION)

.PHONY: proto proto-format proto-lint proto-generate vet test test-race verify

proto: proto-format proto-lint proto-generate

proto-format:
	$(BUF) format -w

proto-lint:
	$(BUF) lint

proto-generate:
	$(BUF) generate

vet:
	go -C contracts vet ./...
	go -C services/order vet ./...
	go -C services/product vet ./...
	go -C services/inventory vet ./...

test:
	go -C contracts test ./...
	go -C services/order test ./...
	go -C services/product test ./...
	go -C services/inventory test ./...

test-race:
	go -C contracts test -race ./...
	go -C services/order test -race ./...
	go -C services/product test -race ./...
	go -C services/inventory test -race ./...

verify:
	$(MAKE) vet
	$(MAKE) test
	$(MAKE) test-race
