// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: marketplace/inventory/v1/inventory.proto

package inventoryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ReservationStatus describes the outcome represented by a reservation response.
type ReservationStatus int32

const (
	// RESERVATION_STATUS_UNSPECIFIED represents an absent or unknown status.
	ReservationStatus_RESERVATION_STATUS_UNSPECIFIED ReservationStatus = 0
	// RESERVATION_STATUS_RESERVED means the requested stock is reserved.
	ReservationStatus_RESERVATION_STATUS_RESERVED ReservationStatus = 1
)

// Enum value maps for ReservationStatus.
var (
	ReservationStatus_name = map[int32]string{
		0: "RESERVATION_STATUS_UNSPECIFIED",
		1: "RESERVATION_STATUS_RESERVED",
	}
	ReservationStatus_value = map[string]int32{
		"RESERVATION_STATUS_UNSPECIFIED": 0,
		"RESERVATION_STATUS_RESERVED":    1,
	}
)

func (x ReservationStatus) Enum() *ReservationStatus {
	p := new(ReservationStatus)
	*p = x
	return p
}

func (x ReservationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReservationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_marketplace_inventory_v1_inventory_proto_enumTypes[0].Descriptor()
}

func (ReservationStatus) Type() protoreflect.EnumType {
	return &file_marketplace_inventory_v1_inventory_proto_enumTypes[0]
}

func (x ReservationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReservationStatus.Descriptor instead.
func (ReservationStatus) EnumDescriptor() ([]byte, []int) {
	return file_marketplace_inventory_v1_inventory_proto_rawDescGZIP(), []int{0}
}

// InventoryFailureReason is a machine-readable reason for an Inventory RPC failure.
type InventoryFailureReason int32

const (
	// INVENTORY_FAILURE_REASON_UNSPECIFIED represents an absent or unknown reason.
	InventoryFailureReason_INVENTORY_FAILURE_REASON_UNSPECIFIED InventoryFailureReason = 0
	// INVENTORY_FAILURE_REASON_INSUFFICIENT_STOCK means available stock was too low.
	InventoryFailureReason_INVENTORY_FAILURE_REASON_INSUFFICIENT_STOCK InventoryFailureReason = 1
	// INVENTORY_FAILURE_REASON_RESERVATION_CONFLICT means order_id identifies a different reservation request.
	InventoryFailureReason_INVENTORY_FAILURE_REASON_RESERVATION_CONFLICT InventoryFailureReason = 2
	// INVENTORY_FAILURE_REASON_RESERVATION_EXPIRED means the reservation is no longer valid.
	InventoryFailureReason_INVENTORY_FAILURE_REASON_RESERVATION_EXPIRED InventoryFailureReason = 3
)

// Enum value maps for InventoryFailureReason.
var (
	InventoryFailureReason_name = map[int32]string{
		0: "INVENTORY_FAILURE_REASON_UNSPECIFIED",
		1: "INVENTORY_FAILURE_REASON_INSUFFICIENT_STOCK",
		2: "INVENTORY_FAILURE_REASON_RESERVATION_CONFLICT",
		3: "INVENTORY_FAILURE_REASON_RESERVATION_EXPIRED",
	}
	InventoryFailureReason_value = map[string]int32{
		"INVENTORY_FAILURE_REASON_UNSPECIFIED":          0,
		"INVENTORY_FAILURE_REASON_INSUFFICIENT_STOCK":   1,
		"INVENTORY_FAILURE_REASON_RESERVATION_CONFLICT": 2,
		"INVENTORY_FAILURE_REASON_RESERVATION_EXPIRED":  3,
	}
)

func (x InventoryFailureReason) Enum() *InventoryFailureReason {
	p := new(InventoryFailureReason)
	*p = x
	return p
}

func (x InventoryFailureReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InventoryFailureReason) Descriptor() protoreflect.EnumDescriptor {
	return file_marketplace_inventory_v1_inventory_proto_enumTypes[1].Descriptor()
}

func (InventoryFailureReason) Type() protoreflect.EnumType {
	return &file_marketplace_inventory_v1_inventory_proto_enumTypes[1]
}

func (x InventoryFailureReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InventoryFailureReason.Descriptor instead.
func (InventoryFailureReason) EnumDescriptor() ([]byte, []int) {
	return file_marketplace_inventory_v1_inventory_proto_rawDescGZIP(), []int{1}
}

// ReserveInventoryRequest describes the stock to reserve for one order.
type ReserveInventoryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// order_id is the idempotency identity for the reservation operation.
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Items         []*ReservationItem     `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveInventoryRequest) Reset() {
	*x = ReserveInventoryRequest{}
	mi := &file_marketplace_inventory_v1_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveInventoryRequest) ProtoMessage() {}

func (x *ReserveInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_inventory_v1_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveInventoryRequest.ProtoReflect.Descriptor instead.
func (*ReserveInventoryRequest) Descriptor() ([]byte, []int) {
	return file_marketplace_inventory_v1_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *ReserveInventoryRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ReserveInventoryRequest) GetItems() []*ReservationItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ReserveInventoryRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// ReservationItem is a product and quantity requested for reservation.
type ReservationItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReservationItem) Reset() {
	*x = ReservationItem{}
	mi := &file_marketplace_inventory_v1_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservationItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservationItem) ProtoMessage() {}

func (x *ReservationItem) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_inventory_v1_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservationItem.ProtoReflect.Descriptor instead.
func (*ReservationItem) Descriptor() ([]byte, []int) {
	return file_marketplace_inventory_v1_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *ReservationItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ReservationItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// ReserveInventoryResponse describes a successful stock reservation.
type ReserveInventoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Status        ReservationStatus      `protobuf:"varint,2,opt,name=status,proto3,enum=marketplace.inventory.v1.ReservationStatus" json:"status,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveInventoryResponse) Reset() {
	*x = ReserveInventoryResponse{}
	mi := &file_marketplace_inventory_v1_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveInventoryResponse) ProtoMessage() {}

func (x *ReserveInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_inventory_v1_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveInventoryResponse.ProtoReflect.Descriptor instead.
func (*ReserveInventoryResponse) Descriptor() ([]byte, []int) {
	return file_marketplace_inventory_v1_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *ReserveInventoryResponse) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReserveInventoryResponse) GetStatus() ReservationStatus {
	if x != nil {
		return x.Status
	}
	return ReservationStatus_RESERVATION_STATUS_UNSPECIFIED
}

func (x *ReserveInventoryResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// InventoryErrorDetail carries structured business context for rich gRPC status errors.
type InventoryErrorDetail struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Reason InventoryFailureReason `protobuf:"varint,1,opt,name=reason,proto3,enum=marketplace.inventory.v1.InventoryFailureReason" json:"reason,omitempty"`
	// product_id identifies the relevant product when the failure is product-specific.
	ProductId     *string `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3,oneof" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InventoryErrorDetail) Reset() {
	*x = InventoryErrorDetail{}
	mi := &file_marketplace_inventory_v1_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryErrorDetail) ProtoMessage() {}

func (x *InventoryErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_marketplace_inventory_v1_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryErrorDetail.ProtoReflect.Descriptor instead.
func (*InventoryErrorDetail) Descriptor() ([]byte, []int) {
	return file_marketplace_inventory_v1_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *InventoryErrorDetail) GetReason() InventoryFailureReason {
	if x != nil {
		return x.Reason
	}
	return InventoryFailureReason_INVENTORY_FAILURE_REASON_UNSPECIFIED
}

func (x *InventoryErrorDetail) GetProductId() string {
	if x != nil && x.ProductId != nil {
		return *x.ProductId
	}
	return ""
}

var File_marketplace_inventory_v1_inventory_proto protoreflect.FileDescriptor

const file_marketplace_inventory_v1_inventory_proto_rawDesc = "" +
	"\n" +
	"(marketplace/inventory/v1/inventory.proto\x12\x18marketplace.inventory.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb0\x01\n" +
	"\x17ReserveInventoryRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12?\n" +
	"\x05items\x18\x02 \x03(\v2).marketplace.inventory.v1.ReservationItemR\x05items\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"L\n" +
	"\x0fReservationItem\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"\xc1\x01\n" +
	"\x18ReserveInventoryResponse\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12C\n" +
	"\x06status\x18\x02 \x01(\x0e2+.marketplace.inventory.v1.ReservationStatusR\x06status\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\x93\x01\n" +
	"\x14InventoryErrorDetail\x12H\n" +
	"\x06reason\x18\x01 \x01(\x0e20.marketplace.inventory.v1.InventoryFailureReasonR\x06reason\x12\"\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tH\x00R\tproductId\x88\x01\x01B\r\n" +
	"\v_product_id*X\n" +
	"\x11ReservationStatus\x12\"\n" +
	"\x1eRESERVATION_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bRESERVATION_STATUS_RESERVED\x10\x01*\xd8\x01\n" +
	"\x16InventoryFailureReason\x12(\n" +
	"$INVENTORY_FAILURE_REASON_UNSPECIFIED\x10\x00\x12/\n" +
	"+INVENTORY_FAILURE_REASON_INSUFFICIENT_STOCK\x10\x01\x121\n" +
	"-INVENTORY_FAILURE_REASON_RESERVATION_CONFLICT\x10\x02\x120\n" +
	",INVENTORY_FAILURE_REASON_RESERVATION_EXPIRED\x10\x032\x8d\x01\n" +
	"\x10InventoryService\x12y\n" +
	"\x10ReserveInventory\x121.marketplace.inventory.v1.ReserveInventoryRequest\x1a2.marketplace.inventory.v1.ReserveInventoryResponseBPZNgithub.com/kitphon/marketplace-order-system/contracts/inventory/v1;inventoryv1b\x06proto3"

var (
	file_marketplace_inventory_v1_inventory_proto_rawDescOnce sync.Once
	file_marketplace_inventory_v1_inventory_proto_rawDescData []byte
)

func file_marketplace_inventory_v1_inventory_proto_rawDescGZIP() []byte {
	file_marketplace_inventory_v1_inventory_proto_rawDescOnce.Do(func() {
		file_marketplace_inventory_v1_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_marketplace_inventory_v1_inventory_proto_rawDesc), len(file_marketplace_inventory_v1_inventory_proto_rawDesc)))
	})
	return file_marketplace_inventory_v1_inventory_proto_rawDescData
}

var file_marketplace_inventory_v1_inventory_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_marketplace_inventory_v1_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_marketplace_inventory_v1_inventory_proto_goTypes = []any{
	(ReservationStatus)(0),           // 0: marketplace.inventory.v1.ReservationStatus
	(InventoryFailureReason)(0),      // 1: marketplace.inventory.v1.InventoryFailureReason
	(*ReserveInventoryRequest)(nil),  // 2: marketplace.inventory.v1.ReserveInventoryRequest
	(*ReservationItem)(nil),          // 3: marketplace.inventory.v1.ReservationItem
	(*ReserveInventoryResponse)(nil), // 4: marketplace.inventory.v1.ReserveInventoryResponse
	(*InventoryErrorDetail)(nil),     // 5: marketplace.inventory.v1.InventoryErrorDetail
	(*timestamppb.Timestamp)(nil),    // 6: google.protobuf.Timestamp
}
var file_marketplace_inventory_v1_inventory_proto_depIdxs = []int32{
	3, // 0: marketplace.inventory.v1.ReserveInventoryRequest.items:type_name -> marketplace.inventory.v1.ReservationItem
	6, // 1: marketplace.inventory.v1.ReserveInventoryRequest.expires_at:type_name -> google.protobuf.Timestamp
	0, // 2: marketplace.inventory.v1.ReserveInventoryResponse.status:type_name -> marketplace.inventory.v1.ReservationStatus
	6, // 3: marketplace.inventory.v1.ReserveInventoryResponse.expires_at:type_name -> google.protobuf.Timestamp
	1, // 4: marketplace.inventory.v1.InventoryErrorDetail.reason:type_name -> marketplace.inventory.v1.InventoryFailureReason
	2, // 5: marketplace.inventory.v1.InventoryService.ReserveInventory:input_type -> marketplace.inventory.v1.ReserveInventoryRequest
	4, // 6: marketplace.inventory.v1.InventoryService.ReserveInventory:output_type -> marketplace.inventory.v1.ReserveInventoryResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_marketplace_inventory_v1_inventory_proto_init() }
func file_marketplace_inventory_v1_inventory_proto_init() {
	if File_marketplace_inventory_v1_inventory_proto != nil {
		return
	}
	file_marketplace_inventory_v1_inventory_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_marketplace_inventory_v1_inventory_proto_rawDesc), len(file_marketplace_inventory_v1_inventory_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_marketplace_inventory_v1_inventory_proto_goTypes,
		DependencyIndexes: file_marketplace_inventory_v1_inventory_proto_depIdxs,
		EnumInfos:         file_marketplace_inventory_v1_inventory_proto_enumTypes,
		MessageInfos:      file_marketplace_inventory_v1_inventory_proto_msgTypes,
	}.Build()
	File_marketplace_inventory_v1_inventory_proto = out.File
	file_marketplace_inventory_v1_inventory_proto_goTypes = nil
	file_marketplace_inventory_v1_inventory_proto_depIdxs = nil
}
